#!/usr/bin/env python3
"""Generate src/rules.cpp from TR25.084-concrete-syntax.md.

`--explain <rule>` needs the TR 25.084 productions available at runtime. This
script extracts the formal grammar lines (1)-(151) from the spec and emits them
as a C++ table, so the spec stays the single source of truth and the generated
table cannot drift from it.

Extraction rules:
  - a line matching ^(N) begins rule N
  - continuation lines are the indented, non-blank lines that follow it
    (wrapped productions), up to the next ^(N) line or the closing ``` fence
  - prose lives outside the fences and is deliberately not included

Usage: gen_rules.py <spec.md> <out.cpp>
"""

import re
import sys


def extract(spec_path):
    rules = {}
    current = None
    in_fence = False
    for raw in open(spec_path, encoding="utf-8"):
        line = raw.rstrip("\n")
        m = re.match(r"^\((\d+)\)\s*(.*)$", line)
        if line.startswith("```"):
            in_fence = not in_fence
            current = None
            continue
        if m and in_fence:
            num = int(m.group(1))
            body = m.group(2)
            current = num
            rules[num] = [body]
            continue
        if current is not None and in_fence and line.strip():
            rules[current].append(line)
            continue
        current = None
    return rules


def emit(rules, out_path):
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen_rules.py — do not edit by hand.\n")
        f.write("// Rule productions (1)-(151) extracted from TR25.084-concrete-syntax.md.\n")
        f.write("#include \"explain.h\"\n\n")
        f.write("const RuleDef kRules[] = {\n")
        for num in sorted(rules):
            text = " ".join(t.strip() for t in rules[num])
            text = text.replace("\\", "\\\\").replace('"', '\\"')
            f.write('  {%d, "%s"},\n' % (num, text))
        f.write("};\n")
        f.write("const int kRuleCount = %d;\n" % len(rules))


def main():
    if len(sys.argv) != 3:
        print("usage: gen_rules.py <spec.md> <out.cpp>", file=sys.stderr)
        return 2
    rules = extract(sys.argv[1])
    emit(rules, sys.argv[2])
    return 0


if __name__ == "__main__":
    sys.exit(main())
