#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ross S. - plic: a PL/I compiler targeting LLVM
"""scripts/gen_embed.py — turn libpli.bc into a C++ byte array.

Mirrors how gen_rules.py generates sources; python is already a build dep,
so no binutils (objcopy/sectcreate/rc.exe) is needed on any host.
"""
import sys


def main(src: str, dst: str) -> None:
    with open(src, "rb") as f:
        data = f.read()
    with open(dst, "w") as f:
        f.write("// embedded_runtime.inc (GENERATED by scripts/gen_embed.py)\n")
        f.write("// Do not edit. Regenerated on every build from libpli.bc.\n")
        f.write('extern "C" const unsigned char plic_embedded_libpli_bc[] = {\n')
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
            f.write("  " + row + ",\n")
        f.write("};\n")
        f.write(
            "extern \"C\" const unsigned long plic_embedded_libpli_bc_len = "
            f"{len(data)}UL;\n"
        )


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
