#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ross S. - plic: a PL/I compiler targeting LLVM
"""scripts/gen_embed.py — turn libpli.bc into a C++ byte array.

Mirrors how gen_rules.py generates sources; python is already a build dep,
so no binutils (objcopy/sectcreate/rc.exe) is needed on any host.

Usage: gen_embed.py <input.bc> <output.inc> [target_suffix]
  target_suffix: optional suffix for array names (e.g., "_linux_x86_64")
  If input is /dev/null, generates empty arrays (stub for non-cross builds).
"""
import sys


def main(src: str, dst: str, target_suffix: str = "") -> None:
    if src == "/dev/null":
        # Generate empty stub arrays for non-cross builds
        data = b""
    else:
        with open(src, "rb") as f:
            data = f.read()
    with open(dst, "w") as f:
        f.write("// embedded_runtime.inc (GENERATED by scripts/gen_embed.py)\n")
        f.write("// Do not edit. Regenerated on every build from libpli.bc.\n")
        array_name = f"plic_embedded_libpli_bc{target_suffix}"
        f.write(f'extern "C" const unsigned char {array_name}[] = {{\n')
        for i in range(0, len(data), 16):
            row = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
            f.write("  " + row + ",\n")
        f.write("};\n")
        f.write(
            f'extern "C" const unsigned long {array_name}_len = '
            f"{len(data)}UL;\n"
        )


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: gen_embed.py <input.bc> <output.inc> [target_suffix]", file=sys.stderr)
        sys.exit(1)
    target_suffix = sys.argv[3] if len(sys.argv) > 3 else ""
    main(sys.argv[1], sys.argv[2], target_suffix)
