// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Ross S. - plic: a PL/I compiler targeting LLVM
// embedded_runtime.cpp — materialise the embedded libpli.bc as a buffer.
#include "embedded_runtime.h"

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/TargetParser/Triple.h"

// Generated byte arrays (build/embedded_runtime*.inc via scripts/gen_embed.py).
#include "embedded_runtime.inc"
// Per-target generated arrays (included by CMake at build time).
// These are generated for: _x86_64_unknown_linux_gnu, _aarch64_unknown_linux_gnu,
// _x86_64_pc_windows_gnu, _aarch64_pc_windows_gnu (full triple names with - replaced by _)
// The actual includes are added by CMake based on PLIC_TARGETS.
#ifdef PLIC_HAVE_LINUX_X86_64_RUNTIME
#include "embedded_runtime_x86_64_unknown_linux_gnu.inc"
#endif
#ifdef PLIC_HAVE_LINUX_AARCH64_RUNTIME
#include "embedded_runtime_aarch64_unknown_linux_gnu.inc"
#endif
#ifdef PLIC_HAVE_WINDOWS_X86_64_RUNTIME
#include "embedded_runtime_x86_64_pc_windows_gnu.inc"
#endif
#ifdef PLIC_HAVE_WINDOWS_AARCH64_RUNTIME
#include "embedded_runtime_aarch64_pc_windows_gnu.inc"
#endif

namespace plic {

llvm::MemoryBufferRef getEmbeddedLibPLI() {
  return llvm::MemoryBufferRef(
      llvm::StringRef(reinterpret_cast<const char*>(plic_embedded_libpli_bc),
                      plic_embedded_libpli_bc_len),
      "libpli.bc");
}

size_t embeddedLibPLISize() { return plic_embedded_libpli_bc_len; }

static void addBlobIfDefined(std::vector<RuntimeBlob>& blobs,
                              const unsigned char* data,
                              unsigned long len,
                              const char* target) {
  if (data && len > 0) {
    blobs.push_back({data, static_cast<size_t>(len), target});
  }
}

std::vector<RuntimeBlob> getEmbeddedRuntimeBlobs() {
  std::vector<RuntimeBlob> blobs;
  // Default (host) blob - always present
  addBlobIfDefined(blobs, plic_embedded_libpli_bc, plic_embedded_libpli_bc_len, PLIC_TARGET_TRIPLE);
  // Per-target blobs (conditionally compiled based on CMake config)
#ifdef PLIC_HAVE_LINUX_X86_64_RUNTIME
  addBlobIfDefined(blobs, plic_embedded_libpli_bc_x86_64_unknown_linux_gnu, plic_embedded_libpli_bc_x86_64_unknown_linux_gnu_len, "x86_64-unknown-linux-gnu");
#endif
#ifdef PLIC_HAVE_LINUX_AARCH64_RUNTIME
  addBlobIfDefined(blobs, plic_embedded_libpli_bc_aarch64_unknown_linux_gnu, plic_embedded_libpli_bc_aarch64_unknown_linux_gnu_len, "aarch64-unknown-linux-gnu");
#endif
#ifdef PLIC_HAVE_WINDOWS_X86_64_RUNTIME
  addBlobIfDefined(blobs, plic_embedded_libpli_bc_x86_64_pc_windows_gnu, plic_embedded_libpli_bc_x86_64_pc_windows_gnu_len, "x86_64-pc-windows-gnu");
#endif
#ifdef PLIC_HAVE_WINDOWS_AARCH64_RUNTIME
  addBlobIfDefined(blobs, plic_embedded_libpli_bc_aarch64_pc_windows_gnu, plic_embedded_libpli_bc_aarch64_pc_windows_gnu_len, "aarch64-pc-windows-gnu");
#endif
  return blobs;
}

const RuntimeBlob* selectRuntimeForTarget(const llvm::Triple& t) {
  static const std::vector<RuntimeBlob> blobs = getEmbeddedRuntimeBlobs();
  const std::string tripleStr = t.getTriple();
  for (const auto& blob : blobs) {
    if (blob.target == tripleStr) {
      return &blob;
    }
  }
  // Fallback to default blob
  for (const auto& blob : blobs) {
    if (blob.target == PLIC_TARGET_TRIPLE) {
      return &blob;
    }
  }
  return nullptr;
}

} // namespace plic
