// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Ross S. - plic: a PL/I compiler targeting LLVM
// embedded_runtime.cpp — materialise the embedded libpli.bc as a buffer.
#include "embedded_runtime.h"

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/MemoryBuffer.h"

// Generated byte array (build/embedded_runtime.inc via scripts/gen_embed.py).
#include "embedded_runtime.inc"

llvm::MemoryBufferRef plic::getEmbeddedLibPLI() {
  return llvm::MemoryBufferRef(
      llvm::StringRef(reinterpret_cast<const char*>(plic_embedded_libpli_bc),
                      plic_embedded_libpli_bc_len),
      "libpli.bc");
}

size_t plic::embeddedLibPLISize() { return plic_embedded_libpli_bc_len; }
