#include "irgen.h"
#include <cstdio>
#include <cstring>

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------
static std::string irEscape(const std::string &s) {
  static const char *hex = "0123456789ABCDEF";
  std::string out;
  for (unsigned char c : s) {
    if (c == '\\' || c == '"' || c < 0x20 || c >= 0x7F) {
      out += '\\';
      out += hex[c >> 4];
      out += hex[c & 0xF];
    } else {
      out += (char)c;
    }
  }
  return out;
}

static std::string fmtDouble(double d) {
  // LLVM accepts hexadecimal float literals; use them to avoid any loss.
  unsigned long long bits;
  static_assert(sizeof(bits) == sizeof(d), "double must be 64-bit");
  memcpy(&bits, &d, sizeof(bits));
  char buf[32];
  snprintf(buf, sizeof(buf), "0x%016llX", bits);
  return buf;
}

std::string IRGen::fresh(const char *prefix) {
  return std::string("%") + prefix + "." + std::to_string(n_++);
}

void IRGen::emitLabel(const std::string &name) {
  if (!terminated_) body_ += "  br label %" + name + "\n";
  body_ += name + ":\n";
  terminated_ = false;
}

void IRGen::branch(const std::string &target) {
  if (!terminated_) {
    body_ += "  br label %" + target + "\n";
    terminated_ = true;
  }
}

std::string IRGen::globalString(const std::string &s) {
  auto it = strLits_.find(s);
  if (it != strLits_.end()) return it->second;
  std::string name = "@.str." + std::to_string(strLits_.size());
  size_t n = s.size() ? s.size() : 1;
  module_ += name + " = private unnamed_addr constant [" + std::to_string(n) +
             " x i8] c\"" + irEscape(s.empty() ? std::string(" ") : s) + "\"\n";
  strLits_[s] = name;
  return name;
}

// ---------------------------------------------------------------------------
// module
// ---------------------------------------------------------------------------
std::string IRGen::run(Program &prog) {
  module_ = ";; Generated by plic (PL/I -> LLVM), M0 wireframe\n";
  if (!triple_.empty()) module_ += "target triple = \"" + triple_ + "\"\n";
  module_ += "\n";

  emitGlobals();

  for (auto &p : prog.procs) emitProc(p.get());

  // C entry point: initialise the runtime, invoke the MAIN procedure,
  // terminate normally (this is where FINISH would be raised, see M5).
  if (prog.mainProc) {
    if (!prog.mainProc->params.empty())
      d_.error(prog.mainProc->loc,
               "parameters on the MAIN procedure are not implemented in this stage", "(2)");
    funcs_ += "define i32 @main() {\nentry:\n";
    funcs_ += "  call void @pli_rt_init()\n";
    funcs_ += "  call void " + prog.mainProc->irName + "()\n";
    funcs_ += "  call void @pli_rt_fini()\n";
    funcs_ += "  ret i32 0\n}\n\n";
  }

  // Forward declarations for external C entries (DECLARE ... ENTRY, rule
  // (38)). PL/I passes arguments by reference, so each parameter is a `ptr`.
  std::string decls;
  for (Symbol *e : sema_.entries()) {
    std::string sig;
    for (size_t i = 0; i < e->entryParams.size(); ++i) {
      if (i) sig += ", ";
      sig += "ptr";
    }
    decls += "declare void " + e->irName + "(" + sig + ")\n";
  }
  decls +=
      "\n; ---- PL/I runtime (libpli) ----\n"
      "declare void @pli_rt_init()\n"
      "declare void @pli_rt_fini()\n"
      "declare void @pli_stop()\n"
      "declare void @pli_put_skip(i64)\n"
      "declare void @pli_put_page()\n"
      "declare void @pli_put_list_char(ptr, i64)\n"
      "declare void @pli_put_list_fixed(i64)\n"
      "declare void @pli_put_list_float(double)\n"
      "declare void @pli_put_list_bit(i8)\n"
      "declare void @pli_assign_char(ptr, i64, ptr, i64)\n"
      "declare i64 @pli_assign_varying(ptr, i64, ptr, i64)\n"
      "declare void @pli_concat(ptr, ptr, i64, ptr, i64)\n"
      "declare void @pli_substr(ptr, i64, ptr, i64, i64, i64)\n"
      "declare i64 @pli_index(ptr, i64, ptr, i64)\n"
      "declare i64 @pli_mod_ll(i64, i64)\n"
      "declare double @pli_mod_dd(double, double)\n"
      "declare double @pli_round(double, i64)\n"
      "declare void @pli_repeat(ptr, i64, ptr, i64, i64)\n"
      "declare i64 @pli_verify(ptr, i64, ptr, i64)\n"
      "declare void @pli_translate(ptr, i64, ptr, i64, ptr, i64, ptr, i64)\n"
      "declare void @pli_high(ptr, i64)\n"
      "declare void @pli_low(ptr, i64)\n"
      "declare void @pli_date(ptr, i64)\n"
      "declare void @pli_time(ptr, i64)\n"
      "declare i32 @pli_cmp_char(ptr, i64, ptr, i64)\n"
      "declare double @llvm.pow.f64(double, double)\n"
      "declare double @llvm.fabs.f64(double)\n";

  return module_ + decls + "\n" + funcs_;
}

void IRGen::emitGlobals() {
  for (Symbol *s : sema_.storage()) {
    if (!s->isStatic || s->kind != Symbol::Var) continue;
    const Type &t = s->ty;
    const Expr *ini = s->initExpr;  // INITIAL constant, rule (26)
    std::string init;
    switch (t.k) {
      case TK::FixedBin:
      case TK::FixedDec: {
        long long v = 0;
        if (ini) v = ini->kind == Expr::FltLit ? (long long)ini->fval
                   : ini->kind == Expr::BitLit ? (!ini->sval.empty() && ini->sval[0] == '1')
                   : ini->ival;
        init = std::to_string(v);
        break;
      }
      case TK::Float: {
        double v = 0;
        if (ini) v = ini->kind == Expr::FltLit ? ini->fval : (double)ini->ival;
        init = fmtDouble(v);
        break;
      }
      case TK::Bit: {
        int v = 0;
        if (ini) v = ini->kind == Expr::BitLit ? (!ini->sval.empty() && ini->sval[0] == '1')
                   : (ini->ival != 0 || ini->fval != 0);
        init = std::to_string(v);
        break;
      }
      case TK::Char: {
        // M0 blank-fills character storage; the spec leaves uninitialised
        // AUTOMATIC storage undefined (see ADR-010).
        std::string text(t.len, ' ');
        if (ini) {
          for (int i = 0; i < t.len && i < (int)ini->sval.size(); ++i) text[i] = ini->sval[i];
        }
        if (t.varying) {
          size_t cur = ini ? std::min<size_t>(ini->sval.size(), (size_t)t.len) : 0;
          init = "{ i32 " + std::to_string(cur) + ", [" + std::to_string(t.len) +
                 " x i8] c\"" + irEscape(text) + "\" }";
        } else {
          init = "c\"" + irEscape(text) + "\"";
        }
        break;
      }
      case TK::Void: continue;
    }
    module_ += s->irName + " = internal global " + t.llvmTy() + " " + init + "\n";
  }
  module_ += "\n";
}

std::string IRGen::addressOf(Symbol *sym) {
  return sym->irName;  // globals: @g ; locals: %x.addr ; params: %x.ptr
}

void IRGen::allocaLocals(Proc *p) {
  for (Symbol *s : p->localSyms) {
    if (s->kind != Symbol::Var) continue;
    body_ += "  " + s->irName + " = alloca " + s->ty.llvmTy() + "\n";
    if (s->ty.isChar()) {  // blank fill
      std::string blanks(s->ty.len, ' ');
      std::string g = globalString(blanks);
      if (s->ty.varying) {
        std::string lenp = fresh("lenp");
        body_ += "  " + lenp + " = getelementptr inbounds " + s->ty.llvmTy() + ", ptr " +
                 s->irName + ", i32 0, i32 0\n";
        body_ += "  store i32 0, ptr " + lenp + "\n";
      } else {
        body_ += "  call void @pli_assign_char(ptr " + s->irName + ", i64 " +
                 std::to_string(s->ty.len) + ", ptr " + g + ", i64 0)\n";
      }
    }
  }
}

// Assign an LLVM block name to every labelled statement (rule (64)) so a GO TO
// (rule (77)) can branch to it. Multiple labels on one statement alias one block.
void IRGen::collectGotoBlocks(Stmt *s) {
  if (!s) return;
  if (!s->labels.empty()) {
    std::string blk = "L" + std::to_string(n_++);
    for (const std::string &l : s->labels) labelBlocks_[l] = blk;
  }
  if (s->thenS) collectGotoBlocks(s->thenS.get());
  if (s->elseS) collectGotoBlocks(s->elseS.get());
  for (auto &b : s->body) collectGotoBlocks(b.get());
}

void IRGen::emitProc(Proc *p) {
  curProc_ = p;
  body_.clear();
  terminated_ = false;
  labelBlocks_.clear();
  for (auto &st : p->body) collectGotoBlocks(st.get());

  if (p->isFunction && p->retTy.isChar()) {
    d_.error(p->loc, "character-valued functions are not implemented in this stage", "(34)");
  }
  const std::string retLLVM = p->isFunction ? p->retTy.llvmTy() : "void";

  std::string params;
  for (size_t i = 0; i < p->paramSyms.size(); ++i) {
    if (i) params += ", ";
    params += "ptr " + p->paramSyms[i]->irName;
  }

  body_ += "entry:\n";
  allocaLocals(p);

  // INITIAL attribute on AUTOMATIC variables (rule 26).
  for (auto &st : p->body) {
    if (st && st->kind == Stmt::Declare)
      for (auto &item : st->decls)
        if (item.init && item.sym && !item.sym->isStatic) {
          Val v = emitExpr(item.init.get());
          storeTo(item.sym, v, item.loc);
        }
  }

  for (auto &st : p->body) emitStmt(st.get());

  if (!terminated_) {
    if (p->isFunction)
      body_ += "  ret " + retLLVM + " 0\n";  // fall-off: return a zero value
    else
      body_ += "  ret void\n";
  }

  funcs_ += "define internal " + retLLVM + " " + p->irName + "(" + params + ") {\n" + body_ + "}\n\n";
  curProc_ = nullptr;
}

// ---------------------------------------------------------------------------
// statements
// ---------------------------------------------------------------------------
void IRGen::emitStmt(Stmt *s) {
  if (!s) return;
  // A labelled statement is a GO TO target (rule (77)) and must begin a new
  // basic block, whether reached by fall-through or by a branch.
  if (!s->labels.empty()) {
    emitLabel(labelBlocks_[s->labels.front()]);
    terminated_ = false;
  } else if (terminated_) {
    // Unreachable code: PL/I allows it (e.g. after STOP); start a new block.
    emitLabel(fresh("dead").substr(1));
  }
  switch (s->kind) {
    case Stmt::Null:
    case Stmt::Declare:
      break;
    case Stmt::Assign: emitAssign(s); break;
    case Stmt::If: emitIf(s); break;
    case Stmt::Group:
    case Stmt::Begin:  // a block executes its body as a group (rule (68))
      for (auto &b : s->body) emitStmt(b.get());
      break;
    case Stmt::DoWhile: emitDoWhile(s); break;
    case Stmt::DoIter: emitDoIter(s); break;
    case Stmt::Put: emitPut(s); break;
    case Stmt::CallS: emitCall(s); break;
    case Stmt::Return: {
      if (curProc_->isFunction) {
        // rule (81): RETURN(value) supplies the function result.
        Val v = emitExpr(s->value.get());
        Val rv = convert(v, curProc_->retTy, s->loc);
        std::string reg = rv.reg;
        if (curProc_->retTy.isBit()) {  // BIT returns are held in i8
          std::string z = fresh("retz");
          body_ += "  " + z + " = zext i1 " + reg + " to i8\n";
          reg = z;
        }
        emit("ret " + curProc_->retTy.llvmTy() + " " + reg);
      } else {
        emit("ret void");
      }
      terminated_ = true;
      break;
    }
    case Stmt::Stop:
      emit("call void @pli_stop()");
      emit("unreachable");
      terminated_ = true;
      break;
    case Stmt::Leave:
      break;
    case Stmt::Goto:
      // rule (77): unconditional branch to the labelled statement.
      emit("br label %" + labelBlocks_[s->name]);
      terminated_ = true;
      break;
  }
}

void IRGen::emitAssign(Stmt *s) {
  if (!s->target || s->target->kind != Expr::VarRef || !s->target->sym) return;
  Val v = emitExpr(s->value.get());
  storeTo(s->target->sym, v, s->loc);
}

void IRGen::emitIf(Stmt *s) {
  Val c = emitExpr(s->cond.get());
  std::string cond = toI1(c, s->loc);
  std::string id = std::to_string(n_++);
  std::string thenL = "if.then." + id, elseL = "if.else." + id, endL = "if.end." + id;
  emit("br i1 " + cond + ", label %" + thenL + ", label %" + (s->elseS ? elseL : endL));
  terminated_ = true;

  emitLabel(thenL);
  emitStmt(s->thenS.get());
  branch(endL);

  if (s->elseS) {
    emitLabel(elseL);
    emitStmt(s->elseS.get());
    branch(endL);
  }
  emitLabel(endL);
}

void IRGen::emitDoWhile(Stmt *s) {
  std::string id = std::to_string(n_++);
  std::string condL = "do.cond." + id, bodyL = "do.body." + id, endL = "do.end." + id;
  branch(condL);
  emitLabel(condL);
  Val c = emitExpr(s->cond.get());
  emit("br i1 " + toI1(c, s->loc) + ", label %" + bodyL + ", label %" + endL);
  terminated_ = true;
  emitLabel(bodyL);
  for (auto &b : s->body) emitStmt(b.get());
  branch(condL);
  emitLabel(endL);
}

// DO v = e1 [TO e2] [BY e3] [WHILE(e4)];                    rules (71)-(73)
// e1/e2/e3 are evaluated once, before the first iteration.
void IRGen::emitDoIter(Stmt *s) {
  Symbol *ctl = s->sym;
  if (!ctl) return;
  const Type &ct = ctl->ty;
  std::string id = std::to_string(n_++);

  Val from = emitExpr(s->from.get());
  storeTo(ctl, from, s->loc);

  std::string toAddr, byAddr;
  if (s->to) {
    Val to = convert(emitExpr(s->to.get()), ct, s->loc);
    toAddr = "%do.to." + id;
    body_ += "  " + toAddr + " = alloca " + ct.llvmTy() + "\n";
    storeScalarTo(toAddr, ct, to);
  }
  Val by;
  if (s->by) {
    by = convert(emitExpr(s->by.get()), ct, s->loc);
  } else {
    by.ty = ct;
    by.reg = ct.k == TK::Float ? fmtDouble(1.0) : "1";
  }
  byAddr = "%do.by." + id;
  body_ += "  " + byAddr + " = alloca " + ct.llvmTy() + "\n";
  storeScalarTo(byAddr, ct, by);

  std::string condL = "do.cond." + id, bodyL = "do.body." + id,
              stepL = "do.step." + id, endL = "do.end." + id,
              upL = "do.up." + id, downL = "do.down." + id, testL = "do.test." + id;

  branch(condL);
  emitLabel(condL);

  if (s->to) {
    // Direction depends on the sign of BY, which may be dynamic.
    Val cv = loadSym(ctl, ct);
    std::string tv = fresh("to");
    body_ += "  " + tv + " = load " + ct.llvmTy() + ", ptr " + toAddr + "\n";
    std::string bv = fresh("by");
    body_ += "  " + bv + " = load " + ct.llvmTy() + ", ptr " + byAddr + "\n";
    std::string zero = ct.k == TK::Float ? fmtDouble(0.0) : "0";
    std::string neg = fresh("negstep");
    if (ct.k == TK::Float)
      body_ += "  " + neg + " = fcmp olt double " + bv + ", " + zero + "\n";
    else
      body_ += "  " + neg + " = icmp slt " + ct.llvmTy() + " " + bv + ", " + zero + "\n";
    emit("br i1 " + neg + ", label %" + downL + ", label %" + upL);
    terminated_ = true;

    emitLabel(upL);
    std::string cu = fresh("cmpup");
    if (ct.k == TK::Float)
      body_ += "  " + cu + " = fcmp ole double " + cv.reg + ", " + tv + "\n";
    else
      body_ += "  " + cu + " = icmp sle " + ct.llvmTy() + " " + cv.reg + ", " + tv + "\n";
    emit("br i1 " + cu + ", label %" + testL + ", label %" + endL);
    terminated_ = true;

    emitLabel(downL);
    std::string cd = fresh("cmpdn");
    if (ct.k == TK::Float)
      body_ += "  " + cd + " = fcmp oge double " + cv.reg + ", " + tv + "\n";
    else
      body_ += "  " + cd + " = icmp sge " + ct.llvmTy() + " " + cv.reg + ", " + tv + "\n";
    emit("br i1 " + cd + ", label %" + testL + ", label %" + endL);
    terminated_ = true;

    emitLabel(testL);
  }

  if (s->cond) {  // WHILE clause
    Val w = emitExpr(s->cond.get());
    emit("br i1 " + toI1(w, s->loc) + ", label %" + bodyL + ", label %" + endL);
    terminated_ = true;
  } else {
    branch(bodyL);
  }

  emitLabel(bodyL);
  for (auto &b : s->body) emitStmt(b.get());
  branch(stepL);

  emitLabel(stepL);
  Val cv = loadSym(ctl, ct);
  std::string bv = fresh("by");
  body_ += "  " + bv + " = load " + ct.llvmTy() + ", ptr " + byAddr + "\n";
  std::string nx = fresh("next");
  if (ct.k == TK::Float)
    body_ += "  " + nx + " = fadd double " + cv.reg + ", " + bv + "\n";
  else
    body_ += "  " + nx + " = add " + ct.llvmTy() + " " + cv.reg + ", " + bv + "\n";
  Val nv;
  nv.ty = ct;
  nv.reg = nx;
  storeTo(ctl, nv, s->loc);
  branch(condL);

  emitLabel(endL);
}

void IRGen::emitPut(Stmt *s) {
  // Options take effect before data transmission (Y33-6003 PUT, rule 5).
  if (s->page) emit("call void @pli_put_page()");
  if (s->skip) {
    std::string n = "1";
    if (s->skipCount) {
      Val v = emitExpr(s->skipCount.get());
      n = toI64(v);
    }
    emit("call void @pli_put_skip(i64 " + n + ")");
  }
  for (auto &item : s->items) {
    Val v = emitExpr(item.get());
    switch (v.ty.k) {
      case TK::Char:
        emit("call void @pli_put_list_char(ptr " + v.ptr + ", i64 " + v.len + ")");
        break;
      case TK::Float:
        emit("call void @pli_put_list_float(double " + v.reg + ")");
        break;
      case TK::Bit: {
        std::string b = fresh("bit");
        body_ += "  " + b + " = zext i1 " + v.reg + " to i8\n";
        emit("call void @pli_put_list_bit(i8 " + b + ")");
        break;
      }
      case TK::FixedBin:
      case TK::FixedDec:
        emit("call void @pli_put_list_fixed(i64 " + toI64(v) + ")");
        break;
      case TK::Void:
        break;
    }
  }
}

void IRGen::emitCall(Stmt *s) {
  if (!s->sym) return;
  Symbol *calleeSym = s->sym;
  Proc *callee = calleeSym->proc;
  // A defined procedure uses its mangled Proc symbol; an external C entry
  // uses the ProcName symbol's irName (@NAME).
  const std::string calleeName = callee ? callee->irName : calleeSym->irName;
  std::string args;
  for (size_t i = 0; i < s->args.size(); ++i) {
    Expr *a = s->args[i].get();
    // The expected parameter type comes from the procedure's DECLAREd
    // parameters, or (for an external C entry) its ENTRY descriptor.
    Type pty;
    if (callee) {
      if (i < callee->paramSyms.size()) pty = callee->paramSyms[i]->ty;
      else break;
    } else {
      if (i < calleeSym->entryParams.size()) pty = calleeSym->entryParams[i];
      else break;
    }
    std::string addr;
    bool direct = a->kind == Expr::VarRef && a->sym && a->sym->kind != Symbol::ProcName &&
                  a->sym->ty.k == pty.k && a->sym->ty.len == pty.len &&
                  a->sym->ty.prec == pty.prec && a->sym->ty.varying == pty.varying;
    if (direct) {
      // True by-reference passing (PL/I default).
      addr = addressOf(a->sym);
    } else {
      // Conversion required: pass a dummy argument (Y33-6003 dummy arguments).
      addr = fresh("dummy");
      body_ += "  " + addr + " = alloca " + pty.llvmTy() + "\n";
      Val v = emitExpr(a);
      if (pty.isChar()) {
        Val cv = v;
        if (pty.varying) {
          std::string dp = fresh("vdata");
          body_ += "  " + dp + " = getelementptr inbounds " + pty.llvmTy() + ", ptr " + addr +
                   ", i32 0, i32 1\n";
          std::string ln = fresh("vlen");
          body_ += "  " + ln + " = call i64 @pli_assign_varying(ptr " + dp + ", i64 " +
                   std::to_string(pty.len) + ", ptr " + cv.ptr + ", i64 " + cv.len + ")\n";
          std::string lp = fresh("vlenp");
          body_ += "  " + lp + " = getelementptr inbounds " + pty.llvmTy() + ", ptr " + addr +
                   ", i32 0, i32 0\n";
          std::string t32 = fresh("l32");
          body_ += "  " + t32 + " = trunc i64 " + ln + " to i32\n";
          body_ += "  store i32 " + t32 + ", ptr " + lp + "\n";
        } else {
          body_ += "  call void @pli_assign_char(ptr " + addr + ", i64 " +
                   std::to_string(pty.len) + ", ptr " + cv.ptr + ", i64 " + cv.len + ")\n";
        }
      } else {
        Val cv = convert(v, pty, a->loc);
        storeScalarTo(addr, pty, cv);
      }
    }
    if (!args.empty()) args += ", ";
    args += "ptr " + addr;
  }
  emit("call void " + calleeName + "(" + args + ")");
}

// ---------------------------------------------------------------------------
// loads / stores
// ---------------------------------------------------------------------------
Val IRGen::loadSym(Symbol *sym, const Type &ty) {
  Val v;
  v.ty = ty;
  std::string addr = addressOf(sym);
  if (ty.isChar()) {
    if (ty.varying) {
      std::string dp = fresh("vdata");
      body_ += "  " + dp + " = getelementptr inbounds " + ty.llvmTy() + ", ptr " + addr +
               ", i32 0, i32 1\n";
      std::string lp = fresh("vlenp");
      body_ += "  " + lp + " = getelementptr inbounds " + ty.llvmTy() + ", ptr " + addr +
               ", i32 0, i32 0\n";
      std::string l32 = fresh("l32");
      body_ += "  " + l32 + " = load i32, ptr " + lp + "\n";
      std::string l64 = fresh("l64");
      body_ += "  " + l64 + " = sext i32 " + l32 + " to i64\n";
      v.ptr = dp;
      v.len = l64;
    } else {
      v.ptr = addr;
      v.len = std::to_string(ty.len);
    }
    return v;
  }
  std::string r = fresh("ld");
  body_ += "  " + r + " = load " + ty.llvmTy() + ", ptr " + addr + "\n";
  if (ty.isBit()) {
    std::string b = fresh("b1");
    body_ += "  " + b + " = trunc i8 " + r + " to i1\n";
    v.reg = b;
  } else {
    v.reg = r;
  }
  return v;
}

void IRGen::storeScalarTo(const std::string &addr, const Type &ty, const Val &v) {
  std::string val = v.reg;
  if (ty.isBit()) {
    std::string z = fresh("z8");
    body_ += "  " + z + " = zext i1 " + val + " to i8\n";
    val = z;
  }
  body_ += "  store " + ty.llvmTy() + " " + val + ", ptr " + addr + "\n";
}

void IRGen::storeTo(Symbol *sym, const Val &v, SourceLoc loc) {
  const Type &dt = sym->ty;
  std::string addr = addressOf(sym);
  if (dt.isChar()) {
    if (!v.ty.isChar()) {
      d_.error(loc, "conversion from " + v.ty.desc() + " to " + dt.desc() +
               " is not implemented in this stage", "(86)");
      return;
    }
    if (dt.varying) {
      std::string dp = fresh("vdata");
      body_ += "  " + dp + " = getelementptr inbounds " + dt.llvmTy() + ", ptr " + addr +
               ", i32 0, i32 1\n";
      std::string ln = fresh("vlen");
      body_ += "  " + ln + " = call i64 @pli_assign_varying(ptr " + dp + ", i64 " +
               std::to_string(dt.len) + ", ptr " + v.ptr + ", i64 " + v.len + ")\n";
      std::string lp = fresh("vlenp");
      body_ += "  " + lp + " = getelementptr inbounds " + dt.llvmTy() + ", ptr " + addr +
               ", i32 0, i32 0\n";
      std::string t32 = fresh("l32");
      body_ += "  " + t32 + " = trunc i64 " + ln + " to i32\n";
      body_ += "  store i32 " + t32 + ", ptr " + lp + "\n";
    } else {
      body_ += "  call void @pli_assign_char(ptr " + addr + ", i64 " + std::to_string(dt.len) +
               ", ptr " + v.ptr + ", i64 " + v.len + ")\n";
    }
    return;
  }
  Val cv = convert(v, dt, loc);
  storeScalarTo(addr, dt, cv);
}

// ---------------------------------------------------------------------------
// conversions (the M0 subset of the PL/I conversion rules)
// ---------------------------------------------------------------------------
Val IRGen::convert(const Val &v, const Type &dst, SourceLoc loc) {
  Val out;
  out.ty = dst;
  if (v.ty.isChar() || dst.isChar()) {
    if (v.ty.isChar() && dst.isChar()) return v;
    d_.error(loc, "conversion between " + v.ty.desc() + " and " + dst.desc() +
             " is not implemented in this stage", "(86)");
    out.reg = "0";
    return out;
  }

  const bool srcFloat = v.ty.k == TK::Float;
  const bool dstFloat = dst.k == TK::Float;
  const bool srcBit = v.ty.isBit();
  const bool dstBit = dst.isBit();

  if (dstBit) {
    out.reg = toI1(v, loc);
    return out;
  }
  if (srcBit) {  // BIT -> arithmetic
    std::string r = fresh("cvt");
    if (dstFloat) {
      std::string z = fresh("z");
      body_ += "  " + z + " = zext i1 " + v.reg + " to i32\n";
      body_ += "  " + r + " = sitofp i32 " + z + " to double\n";
    } else {
      body_ += "  " + r + " = zext i1 " + v.reg + " to " + dst.llvmTy() + "\n";
    }
    out.reg = r;
    return out;
  }
  if (srcFloat && dstFloat) return v;
  if (srcFloat && !dstFloat) {  // FLOAT -> FIXED truncates toward zero
    std::string r = fresh("cvt");
    body_ += "  " + r + " = fptosi double " + v.reg + " to " + dst.llvmTy() + "\n";
    out.reg = r;
    return out;
  }
  if (!srcFloat && dstFloat) {
    std::string r = fresh("cvt");
    body_ += "  " + r + " = sitofp " + v.ty.llvmTy() + " " + v.reg + " to double\n";
    out.reg = r;
    return out;
  }
  // FIXED -> FIXED: adjust width
  if (v.ty.intBits() == dst.intBits()) {
    out.reg = v.reg;
    return out;
  }
  std::string r = fresh("cvt");
  if (v.ty.intBits() < dst.intBits())
    body_ += "  " + r + " = sext " + v.ty.llvmTy() + " " + v.reg + " to " + dst.llvmTy() + "\n";
  else
    body_ += "  " + r + " = trunc " + v.ty.llvmTy() + " " + v.reg + " to " + dst.llvmTy() + "\n";
  out.reg = r;
  return out;
}

std::string IRGen::toI1(const Val &v, SourceLoc loc) {
  if (v.ty.isBit()) return v.reg;
  if (v.ty.k == TK::Float) {
    std::string r = fresh("tst");
    body_ += "  " + r + " = fcmp une double " + v.reg + ", " + fmtDouble(0.0) + "\n";
    return r;
  }
  if (v.ty.isNumeric()) {
    std::string r = fresh("tst");
    body_ += "  " + r + " = icmp ne " + v.ty.llvmTy() + " " + v.reg + ", 0\n";
    return r;
  }
  d_.error(loc, "value of type " + v.ty.desc() + " cannot be used as a condition", "(75)");
  return "false";
}

std::string IRGen::toI64(const Val &v) {
  if (v.ty.k == TK::Float) {
    std::string r = fresh("i64");
    body_ += "  " + r + " = fptosi double " + v.reg + " to i64\n";
    return r;
  }
  if (v.ty.isBit()) {
    std::string r = fresh("i64");
    body_ += "  " + r + " = zext i1 " + v.reg + " to i64\n";
    return r;
  }
  if (v.ty.intBits() == 64) return v.reg;
  std::string r = fresh("i64");
  body_ += "  " + r + " = sext " + v.ty.llvmTy() + " " + v.reg + " to i64\n";
  return r;
}

Val IRGen::charTemp(int len) {
  Val v;
  v.ty = Type::chr(len);
  v.ptr = fresh("cbuf");
  body_ += "  " + v.ptr + " = alloca [" + std::to_string(len) + " x i8]\n";
  v.len = std::to_string(len);
  return v;
}

// ---------------------------------------------------------------------------
// expressions
// ---------------------------------------------------------------------------
Val IRGen::emitExpr(Expr *e) {
  Val v;
  if (!e) return v;
  switch (e->kind) {
    case Expr::IntLit:
      v.ty = e->ty;
      v.reg = std::to_string(e->ival);
      return v;
    case Expr::FltLit:
      v.ty = e->ty;
      v.reg = fmtDouble(e->fval);
      return v;
    case Expr::CharLit: {
      v.ty = e->ty;
      v.ptr = globalString(e->sval);
      v.len = std::to_string(e->sval.size());
      return v;
    }
    case Expr::BitLit:
      v.ty = Type::bit(1);
      v.reg = (!e->sval.empty() && e->sval[0] == '1') ? "true" : "false";
      return v;
    case Expr::VarRef:
      if (!e->sym) { v.ty = e->ty; v.reg = "0"; return v; }
      return loadSym(e->sym, e->sym->ty);
    case Expr::Call: {
      // SUBSTR built-in (M2): substr(s, i, n) — copy n chars of s starting at
      // the 1-based position i into a fresh buffer.
      if (e->name == "SUBSTR") {
        Val s = emitExpr(e->args[0].get());
        Val start = emitExpr(e->args[1].get());
        Val len = emitExpr(e->args[2].get());
        Val out = charTemp(e->ty.len);
        body_ += "  call void @pli_substr(ptr " + out.ptr + ", i64 " + out.len +
                 ", ptr " + s.ptr + ", i64 " + s.len + ", i64 " + toI64(start) +
                 ", i64 " + toI64(len) + ")\n";
        out.len = std::to_string(e->ty.len);
        return out;
      }
      // INDEX built-in (M2): index(s1, s2) -> FIXED BINARY position (i32).
      if (e->name == "INDEX") {
        Val a = emitExpr(e->args[0].get());
        Val b = emitExpr(e->args[1].get());
        std::string r = fresh("idx");
        body_ += "  " + r + " = call i64 @pli_index(ptr " + a.ptr + ", i64 " + a.len +
                 ", ptr " + b.ptr + ", i64 " + b.len + ")\n";
        std::string t = fresh("idx32");
        body_ += "  " + t + " = trunc i64 " + r + " to i32\n";
        v.ty = e->ty;
        v.reg = t;
        return v;
      }
      // ABS built-in (M2): absolute value; float via llvm.fabs, fixed via the
      // select idiom.
      if (e->name == "ABS") {
        Val a = emitExpr(e->args[0].get());
        const Type &at = a.ty;
        std::string r = fresh("abs");
        if (at.k == TK::Float) {
          body_ += "  " + r + " = call double @llvm.fabs.f64(double " + a.reg + ")\n";
        } else {
          std::string neg = fresh("absneg");
          body_ += "  " + neg + " = sub " + at.llvmTy() + " 0, " + a.reg + "\n";
          std::string cmp = fresh("abscmp");
          body_ += "  " + cmp + " = icmp slt " + at.llvmTy() + " " + a.reg + ", 0\n";
          body_ += "  " + r + " = select i1 " + cmp + ", " + at.llvmTy() + " " + neg +
                   ", " + at.llvmTy() + " " + a.reg + "\n";
        }
        v.ty = e->ty;
        v.reg = r;
        return v;
      }
      // LENGTH built-in (M2): the string value already carries its current
      // length (i64); size it to a FIXED BINARY(31) result.
      if (e->name == "LENGTH") {
        Val a = emitExpr(e->args[0].get());
        std::string t = fresh("len32");
        body_ += "  " + t + " = trunc i64 " + a.len + " to i32\n";
        v.ty = e->ty;
        v.reg = t;
        return v;
      }
      // TRUNC built-in (M2): drop the fractional part toward zero. FLOAT goes
      // through fptosi/sitofp; FIXED is already integral (no-op).
      if (e->name == "TRUNC") {
        Val a = emitExpr(e->args[0].get());
        if (a.ty.k == TK::Float) {
          std::string i = fresh("trunci");
          body_ += "  " + i + " = fptosi double " + a.reg + " to i64\n";
          std::string r = fresh("truncd");
          body_ += "  " + r + " = sitofp i64 " + i + " to double\n";
          v.ty = e->ty;
          v.reg = r;
        } else {
          v = a;
        }
        return v;
      }
      // PRECISION built-in (M2): keep x's value, widen/narrow to the result
      // type when the requested precision changes the FIXED storage width.
      if (e->name == "PRECISION") {
        Val a = emitExpr(e->args[0].get());
        v = convert(a, e->ty, e->loc);
        return v;
      }
      // MIN built-in (M2): convert both operands to the common type and select
      // the smaller.
      if (e->name == "MIN") {
        Val a = emitExpr(e->args[0].get());
        Val b = emitExpr(e->args[1].get());
        const Type &common = e->ty;
        Val av = convert(a, common, e->loc);
        Val bv = convert(b, common, e->loc);
        std::string cmp = fresh("mincmp");
        if (common.k == TK::Float)
          body_ += "  " + cmp + " = fcmp olt double " + av.reg + ", " + bv.reg + "\n";
        else
          body_ += "  " + cmp + " = icmp slt " + common.llvmTy() + " " + av.reg + ", " + bv.reg + "\n";
        std::string r = fresh("min");
        body_ += "  " + r + " = select i1 " + cmp + ", " + common.llvmTy() + " " + av.reg +
                 ", " + common.llvmTy() + " " + bv.reg + "\n";
        v.ty = common;
        v.reg = r;
        return v;
      }
      // MAX built-in (M2): convert both operands to the common type and select
      // the larger.
      if (e->name == "MAX") {
        Val a = emitExpr(e->args[0].get());
        Val b = emitExpr(e->args[1].get());
        const Type &common = e->ty;
        Val av = convert(a, common, e->loc);
        Val bv = convert(b, common, e->loc);
        std::string cmp = fresh("maxcmp");
        if (common.k == TK::Float)
          body_ += "  " + cmp + " = fcmp olt double " + av.reg + ", " + bv.reg + "\n";
        else
          body_ += "  " + cmp + " = icmp slt " + common.llvmTy() + " " + av.reg + ", " + bv.reg + "\n";
        std::string r = fresh("max");
        body_ += "  " + r + " = select i1 " + cmp + ", " + common.llvmTy() + " " + bv.reg +
                 ", " + common.llvmTy() + " " + av.reg + "\n";
        v.ty = common;
        v.reg = r;
        return v;
      }
      // MOD built-in (M2): remainder with the divisor's sign, via the runtime.
      if (e->name == "MOD") {
        Val a = emitExpr(e->args[0].get());
        Val b = emitExpr(e->args[1].get());
        const Type &common = e->ty;
        Val av = convert(a, common, e->loc);
        Val bv = convert(b, common, e->loc);
        std::string r = fresh("mod");
        if (common.k == TK::Float)
          body_ += "  " + r + " = call double @pli_mod_dd(double " + av.reg + ", double " + bv.reg + ")\n";
        else
          body_ += "  " + r + " = call i64 @pli_mod_ll(i64 " + toI64(av) + ", i64 " + toI64(bv) + ")\n";
        v.ty = common;
        if (common.k == TK::Float) {
          v.reg = r;
        } else {
          std::string t = fresh("mod32");
          body_ += "  " + t + " = trunc i64 " + r + " to i32\n";
          v.reg = t;
        }
        return v;
      }
      // MULTIPLY built-in (M2): product of two numerics (like *).
      if (e->name == "MULTIPLY") {
        Val a = emitExpr(e->args[0].get());
        Val b = emitExpr(e->args[1].get());
        const Type &common = e->ty;
        Val av = convert(a, common, e->loc);
        Val bv = convert(b, common, e->loc);
        std::string r = fresh("mul");
        body_ += "  " + r + " = " + (common.k == TK::Float ? "fmul" : "mul") + " " + common.llvmTy() +
                 " " + av.reg + ", " + bv.reg + "\n";
        v.ty = common;
        v.reg = r;
        return v;
      }
      // DIVIDE built-in (M2): quotient of two numerics in floating point
      // (ADR-014; exact decimal division is M2), like the `/` operator.
      if (e->name == "DIVIDE") {
        Val a = emitExpr(e->args[0].get());
        Val b = emitExpr(e->args[1].get());
        const Type &common = e->ty;
        Val av = convert(a, common, e->loc);
        Val bv = convert(b, common, e->loc);
        std::string r = fresh("div");
        body_ += "  " + r + " = fdiv double " + av.reg + ", " + bv.reg + "\n";
        v.ty = common;
        v.reg = r;
        return v;
      }
      // ROUND built-in (M2): round x to n fractional digits, as a FLOAT.
      if (e->name == "ROUND") {
        Val x = emitExpr(e->args[0].get());
        Val n = emitExpr(e->args[1].get());
        Val xd = convert(x, Type::flt(6), e->loc);
        std::string r = fresh("round");
        body_ += "  " + r + " = call double @pli_round(double " + xd.reg + ", i64 " + toI64(n) + ")\n";
        v.ty = e->ty;
        v.reg = r;
        return v;
      }
      // REPEAT built-in (M2): fill a buffer with n copies of s.
      if (e->name == "REPEAT") {
        Val s = emitExpr(e->args[0].get());
        Val n = emitExpr(e->args[1].get());
        Val out = charTemp(e->ty.len);
        body_ += "  call void @pli_repeat(ptr " + out.ptr + ", i64 " + out.len +
                 ", ptr " + s.ptr + ", i64 " + s.len + ", i64 " + toI64(n) + ")\n";
        out.len = std::to_string(e->ty.len);
        return out;
      }
      // VERIFY built-in (M2): position of the first char of s not in t.
      if (e->name == "VERIFY") {
        Val s = emitExpr(e->args[0].get());
        Val t = emitExpr(e->args[1].get());
        std::string r = fresh("ver");
        body_ += "  " + r + " = call i64 @pli_verify(ptr " + s.ptr + ", i64 " + s.len +
                 ", ptr " + t.ptr + ", i64 " + t.len + ")\n";
        std::string x = fresh("ver32");
        body_ += "  " + x + " = trunc i64 " + r + " to i32\n";
        v.ty = e->ty;
        v.reg = x;
        return v;
      }
      // TRANSLATE built-in (M2): map characters of s through the in/out table.
      if (e->name == "TRANSLATE") {
        Val s = emitExpr(e->args[0].get());
        Val out = emitExpr(e->args[1].get());
        Val in = emitExpr(e->args[2].get());
        Val dst = charTemp(e->ty.len);
        body_ += "  call void @pli_translate(ptr " + dst.ptr + ", i64 " + dst.len +
                 ", ptr " + s.ptr + ", i64 " + s.len + ", ptr " + out.ptr + ", i64 " + out.len +
                 ", ptr " + in.ptr + ", i64 " + in.len + ")\n";
        dst.len = std::to_string(e->ty.len);
        return dst;
      }
      // HIGH/LOW built-ins (M2): fill a buffer with the top/bottom character.
      if (e->name == "HIGH" || e->name == "LOW") {
        Val n = emitExpr(e->args[0].get());
        Val out = charTemp(e->ty.len);
        body_ += "  call void @" + (e->name == "HIGH" ? std::string("pli_high") : std::string("pli_low")) +
                 "(ptr " + out.ptr + ", i64 " + toI64(n) + ")\n";
        out.len = std::to_string(e->ty.len);
        return out;
      }
      // DATE/TIME built-ins (M2): fill a buffer with the current date/time.
      if (e->name == "DATE" || e->name == "TIME") {
        Val out = charTemp(e->ty.len);
        body_ += "  call void @" + (e->name == "DATE" ? std::string("pli_date") : std::string("pli_time")) +
                 "(ptr " + out.ptr + ", i64 " + out.len + ")\n";
        out.len = std::to_string(e->ty.len);
        return out;
      }
      // Function reference (rule (123)): call an internal function procedure
      // and take its result as a value.
      if (!e->sym || !e->sym->proc) { v.ty = e->ty; v.reg = "0"; return v; }
      Proc *callee = e->sym->proc;
      const Type &rty = callee->retTy;
      if (rty.isChar()) { v.ty = e->ty; v.reg = "0"; return v; }  // diagnosed in emitProc
      std::string args;
      for (size_t i = 0; i < e->args.size(); ++i) {
        Expr *a = e->args[i].get();
        Type pty;
        if (i < callee->paramSyms.size()) pty = callee->paramSyms[i]->ty;
        else break;
        std::string addr;
        bool direct = a->kind == Expr::VarRef && a->sym && a->sym->kind != Symbol::ProcName &&
                      a->sym->ty.k == pty.k && a->sym->ty.len == pty.len &&
                      a->sym->ty.prec == pty.prec && a->sym->ty.varying == pty.varying;
        if (direct) {
          addr = addressOf(a->sym);
        } else {
          addr = fresh("dummy");
          body_ += "  " + addr + " = alloca " + pty.llvmTy() + "\n";
          Val av = emitExpr(a);
          if (pty.isChar()) {
            Val cv = av;
            if (pty.varying) {
              std::string dp = fresh("vdata");
              body_ += "  " + dp + " = getelementptr inbounds " + pty.llvmTy() + ", ptr " + addr +
                       ", i32 0, i32 1\n";
              std::string ln = fresh("vlen");
              body_ += "  " + ln + " = call i64 @pli_assign_varying(ptr " + dp + ", i64 " +
                       std::to_string(pty.len) + ", ptr " + cv.ptr + ", i64 " + cv.len + ")\n";
              std::string lp = fresh("vlenp");
              body_ += "  " + lp + " = getelementptr inbounds " + pty.llvmTy() + ", ptr " + addr +
                       ", i32 0, i32 0\n";
              std::string t32 = fresh("l32");
              body_ += "  " + t32 + " = trunc i64 " + ln + " to i32\n";
              body_ += "  store i32 " + t32 + ", ptr " + lp + "\n";
            } else {
              body_ += "  call void @pli_assign_char(ptr " + addr + ", i64 " +
                       std::to_string(pty.len) + ", ptr " + cv.ptr + ", i64 " + cv.len + ")\n";
            }
          } else {
            Val cv = convert(av, pty, a->loc);
            storeScalarTo(addr, pty, cv);
          }
        }
        if (!args.empty()) args += ", ";
        args += "ptr " + addr;
      }
      std::string callReg = fresh("fres");
      body_ += "  " + callReg + " = call " + rty.llvmTy() + " " + callee->irName + "(" + args + ")\n";
      v.ty = rty;
      if (rty.isBit()) {
        std::string b = fresh("fb");
        body_ += "  " + b + " = trunc i8 " + callReg + " to i1\n";
        v.reg = b;
      } else {
        v.reg = callReg;
      }
      return v;
    }
    case Expr::Unary: {
      Val a = emitExpr(e->a.get());
      if (e->op == Tok::Not) {
        std::string b = toI1(a, e->loc);
        std::string r = fresh("not");
        body_ += "  " + r + " = xor i1 " + b + ", true\n";
        v.ty = Type::bit(1);
        v.reg = r;
        return v;
      }
      // unary minus
      v.ty = a.ty;
      std::string r = fresh("neg");
      if (a.ty.k == TK::Float)
        body_ += "  " + r + " = fneg double " + a.reg + "\n";
      else
        body_ += "  " + r + " = sub " + a.ty.llvmTy() + " 0, " + a.reg + "\n";
      v.reg = r;
      return v;
    }
    case Expr::Binary: break;
  }

  // ---- binary operators ----
  const Tok op = e->op;

  if (op == Tok::Concat) {                                     // rule (119)
    Val a = emitExpr(e->a.get());
    Val b = emitExpr(e->b.get());
    if (!a.ty.isChar() || !b.ty.isChar()) { v.ty = e->ty; v.reg = "0"; return v; }
    Val out = charTemp(e->ty.len);  // capacity = sum of the maximum lengths
    body_ += "  call void @pli_concat(ptr " + out.ptr + ", ptr " + a.ptr + ", i64 " + a.len +
             ", ptr " + b.ptr + ", i64 " + b.len + ")\n";
    // The current length is the sum of the operands' current lengths, which is
    // dynamic when an operand is VARYING.
    std::string sum = fresh("clen");
    body_ += "  " + sum + " = add i64 " + a.len + ", " + b.len + "\n";
    out.len = sum;
    return out;
  }

  if (op == Tok::Amp || op == Tok::Bar) {                       // rules (116),(115)
    Val a = emitExpr(e->a.get());
    std::string ab = toI1(a, e->loc);
    Val b = emitExpr(e->b.get());
    std::string bb = toI1(b, e->loc);
    std::string r = fresh(op == Tok::Amp ? "and" : "or");
    body_ += "  " + r + " = " + (op == Tok::Amp ? "and" : "or") + " i1 " + ab + ", " + bb + "\n";
    v.ty = Type::bit(1);
    v.reg = r;
    return v;
  }

  const bool isCmp = op == Tok::Eq || op == Tok::Ne || op == Tok::Lt || op == Tok::Le ||
                     op == Tok::Gt || op == Tok::Ge || op == Tok::Ngt || op == Tok::Nlt;

  Val a = emitExpr(e->a.get());
  Val b = emitExpr(e->b.get());

  if (isCmp && a.ty.isChar() && b.ty.isChar()) {                // rule (117)
    std::string c = fresh("scmp");
    body_ += "  " + c + " = call i32 @pli_cmp_char(ptr " + a.ptr + ", i64 " + a.len +
             ", ptr " + b.ptr + ", i64 " + b.len + ")\n";
    const char *pred = "eq";
    switch (op) {
      case Tok::Eq: pred = "eq"; break;
      case Tok::Ne: pred = "ne"; break;
      case Tok::Lt: pred = "slt"; break;
      case Tok::Le: pred = "sle"; break;
      case Tok::Gt: pred = "sgt"; break;
      case Tok::Ge: pred = "sge"; break;
      case Tok::Ngt: pred = "sle"; break;
      case Tok::Nlt: pred = "sge"; break;
      default: break;
    }
    std::string r = fresh("cmp");
    body_ += "  " + r + " = icmp " + pred + " i32 " + c + ", 0\n";
    v.ty = Type::bit(1);
    v.reg = r;
    return v;
  }

  // Arithmetic and arithmetic comparison: convert both operands to a common
  // type first (the "target type" of the conversion rules).
  Type common = isCmp ? arithResultType(a.ty.isBit() ? Type::fixedBin(31, 0) : a.ty,
                                        b.ty.isBit() ? Type::fixedBin(31, 0) : b.ty)
                      : e->ty;
  if (!isCmp && (op == Tok::Slash || op == Tok::Power)) common = Type::flt(e->ty.prec);
  Val av = convert(a, common, e->loc);
  Val bv = convert(b, common, e->loc);
  const bool flt = common.k == TK::Float;
  const std::string ty = common.llvmTy();

  if (isCmp) {
    const char *pred = "eq";
    if (flt) {
      switch (op) {
        case Tok::Eq: pred = "oeq"; break;
        case Tok::Ne: pred = "une"; break;
        case Tok::Lt: pred = "olt"; break;
        case Tok::Le: pred = "ole"; break;
        case Tok::Gt: pred = "ogt"; break;
        case Tok::Ge: pred = "oge"; break;
        case Tok::Ngt: pred = "ole"; break;
        case Tok::Nlt: pred = "oge"; break;
        default: break;
      }
    } else {
      switch (op) {
        case Tok::Eq: pred = "eq"; break;
        case Tok::Ne: pred = "ne"; break;
        case Tok::Lt: pred = "slt"; break;
        case Tok::Le: pred = "sle"; break;
        case Tok::Gt: pred = "sgt"; break;
        case Tok::Ge: pred = "sge"; break;
        case Tok::Ngt: pred = "sle"; break;
        case Tok::Nlt: pred = "sge"; break;
        default: break;
      }
    }
    std::string r = fresh("cmp");
    body_ += "  " + r + " = " + (flt ? "fcmp " : "icmp ") + pred + " " + ty + " " + av.reg +
             ", " + bv.reg + "\n";
    v.ty = Type::bit(1);
    v.reg = r;
    return v;
  }

  std::string r = fresh("bin");
  switch (op) {
    case Tok::Plus:
      body_ += "  " + r + " = " + (flt ? "fadd" : "add") + " " + ty + " " + av.reg + ", " + bv.reg + "\n";
      break;
    case Tok::Minus:
      body_ += "  " + r + " = " + (flt ? "fsub" : "sub") + " " + ty + " " + av.reg + ", " + bv.reg + "\n";
      break;
    case Tok::Star:
      body_ += "  " + r + " = " + (flt ? "fmul" : "mul") + " " + ty + " " + av.reg + ", " + bv.reg + "\n";
      break;
    case Tok::Slash:
      body_ += "  " + r + " = fdiv double " + av.reg + ", " + bv.reg + "\n";
      break;
    case Tok::Power:
      body_ += "  " + r + " = call double @llvm.pow.f64(double " + av.reg + ", double " + bv.reg + ")\n";
      break;
    default:
      body_ += "  " + r + " = add " + ty + " 0, 0\n";
      break;
  }
  v.ty = common;
  v.reg = r;
  return v;
}
